### ISSUE TITLE
Gofish Advanced Search - Missing sections 

### ISSUE THREAD

**Issue by parios815** [VFPX/GoFish#196] opened 2024-03-26 23:51 UTC
## ℹ window 11 pro

- VFP version: 9.0 
- GoFish version: 07.0.18

## 📝 Provide detailed reproduction steps (if any)

1. …installed update of Gofish 
2. …
3. …

### ✔️ missing section of the advanced search... or is this the new update?

_What is the expected result of the above steps?_

### ❌ advanced search is missing sections.

_What is the actual result of the above steps?_

## 📷 Screenshots 
      version 7.0.18 advanced search   
![image](https://github.com/VFPX/GoFish/assets/30445595/709be42d-7324-4e80-a93b-54a187c5cb20)

version 5.2.02
![image](https://github.com/VFPX/GoFish/assets/30445595/fe0e3291-4354-41cd-8107-ba91b291902a)

_Are there any other useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by Jimrnelson** [comment] 2024-03-27 00:07
That is intentional.

The "Advanced" page has been simplified to only include those settings not already present on the main form.

**Comment by parios815** [comment] 2024-03-27 11:22
Ok, please consider issue solve. Didn’t find where it was stated.

Thank you

Sent from my iPhone, Please excuse my brevity.

On Mar 26, 2024, at 17:07, Jimrnelson ***@***.***> wrote:

﻿

That is intentional.

The "Advanced" page has been simplified to only include those settings not already present on the main form.

**Comment by Jimrnelson** [comment] 2024-03-27 13:53
This is a duplicate of #195.

**Closed by Jimrnelson** 2024-03-27 13:53 UTC

**Comment by parios815** [comment] 2024-03-27 14:16
please close ticket...
________________________________
