### ISSUE TITLE
Matched line not highlighted redux

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#40] opened 2022-12-09 18:44 UTC
This is issue #27 again, or really still. This is not fixed for me.

**Comment by Jimrnelson** [comment] 2022-12-09 19:59
Tamar. —Is this always an issue or occasional?I have never had this problem but will be glad to look into it.  Am somewhat familiar with it and wonder about how alignment in the browser works.  When you scroll down is the code properly highlighted?Sent from my iPhoneOn Dec 9, 2022, at 10:44 AM, TamarEGranor ***@***.***> wrote:﻿
This is issue #27 again, or really still. This is not fixed for me.

**Comment by TamarEGranor** [comment] 2022-12-09 20:06
This started with a post-VFF build (I think Lutz's first version) and has persisted. My title isn't quite right. The items are highlighted, but the window isn't scrolled to the first match. So if the first match is near the top, I see it. Otherwise, I have to scroll. This is making me much less productive.

**Comment by Jimrnelson** [comment] 2022-12-09 20:16
That helps.  Sent from my iPhoneOn Dec 9, 2022, at 12:06 PM, TamarEGranor ***@***.***> wrote:﻿
This started with a post-VFF build (I think Lutz's first version) and has persisted. My title isn't quite right. The items are highlighted, but the window isn't scrolled to the first match. So if the first match is near the top, I see it. Otherwise, I have to scroll. This is making me much less productive.

**Comment by lscheffler** [comment] 2022-12-09 20:56
@TamarEGranor Can you check the HTML itself, please.   
On the end there should be a section of well formated JS. If this is all in one line, something is wrong.    
There is somewhere in the source as JS file.  Please check this with an HEX editor. look up the line endings. If they are not CRLF we are still mixed up.    
Basically any file in the source could be checked for this problem.   
Please send me the result of this checks.

This is a problem of different set git environment on coworking computers. Some translate CRLF -> LF on commit and checkout, Others only on one others not. This is a quirky setting for coworking with LINUX target. Ancient crap an Linux that can't deal with CRLF files.  OTOH VFP's `TEXT TO .. TEXTMERGE` can't handle LF terminated lines in strings. And once wrong a good place to create the havoc we have now.    
I thougth  I found a solution, it works now with my comp. I must recheck the settings.

**Comment by lscheffler** [comment] 2022-12-09 21:07
@Jimrnelson The problem is git is reducing CRLF to LF under special settings on one comp and  not recreating CRLF on an  other with different settings. And that VFP's TEXT TO .. TEXTMERGE can't handle LF terminated lines in strings. It elemintes the LF, the string is one line. This is the JS responsible for the scroll textmerged to the HTML's end. As a single line it could not run.

There is not much more to do then transform all the files from LF to CRLF and recompile to restart it working. I try to force the use of the correct settings over different computers, but so far without result. :(

**Comment by TamarEGranor** [comment] 2022-12-09 21:18
The JS section at the bottom looks good, properly formatted and readable. I checked a couple of different examples, just to be sure. In a hex editor (the one that comes with VFP--not a tool I need very often), I see 0D 0A where I'd expect.

**Comment by lscheffler** [comment] 2022-12-10 07:35
@TamarEGranor 

- Please select a larger piece of code with firstmatch well down. Store the HTML chunk to a html file and open in browser of your choice. Is it auto scrolling on open?
   - Could you provide the HTML?   
- Possibly you can get commit 726d4aa4471df643. This is the last before I jumped in. Is this working?
- I never have touched the HTML generation or rendering at all. The error from #27 was clearly from the CRLF / LF problem.

**Comment by lscheffler** [comment] 2022-12-13 08:43
@Tamar If took the code and runned it by GoFishs handler (This is ShowHTMLCodeView, variable lcHTML), it scrolls on my comp. This is version 5.1.008 11/23/2022.
- compiled on my comp under VFPA
- Version from Thor under VFPA
- Version from Thor under VFP9   

all running fine. :(

All I can suggest is try an old version and see if this is running. I have no idea.

**Comment by TamarEGranor** [comment] 2022-12-13 21:47
I never had an issue with GoFish properly scrolling until fairly recently, when it suddenly stopped. How would would I try an old version?

**Comment by lscheffler** [comment] 2022-12-14 05:49
@TamarEGranor this depends on you usage of git.
#### If you use git
#1 clone this repo
#2 run `git checkout 726d4aa4471df643`
#3 the repo is in the state of this commit, this is the source code, the zip and the app are in latest version where I was not involved, complete with source and app
#### If you are not using git
#1 open commit 726d4aa4471df643 in a new tab. 
#2 on top right is a button *Browse files*, click
#3 now there is a button *<>Code*. click
#4 select *download zip*
#5 expand zip, you got the latest version where I was not involved on you comp, complete with source and app   

----
I recommend to use git.

**Comment by TamarEGranor** [comment] 2022-12-14 16:38
Thanks for the detailed instructions. The problem persists in the older version. Guess that suggests something changed in my settings that's causing the relevant code not to run.

**Comment by lscheffler** [comment] 2022-12-15 15:23
Something set to disable JavaScript? In the end, it's just a HTML page with embedded JS using the `window.onload` event to scroll. There is nothing VFP is doing then loading the page into the browser.

@DougHennig We can close this issue, there is no help I can do. :(

**Closed** 2022-12-15 15:32 UTC

**Comment by drFairday** [comment] 2023-01-12 14:39
In a situation like that (fox generated html) I found that this helps:

loRow=document.getElementById("g2152");
loRow.scrollIntoView();

So I'd suggest generating html with one line per id, and running this on the oBrowser object, IOW matching line numbers, not searching.

We discussed this on UT and Lutz asked me to write it here, and so I did.
(btw, this is Dragan, don't know which of the names it asked me to create will be visible...)
