### ISSUE TITLE
Select the control in which text is found when editing

### ISSUE THREAD

**Issue by DougHennig** [VFPX/GoFish#194] opened 2024-03-26 21:45 UTC
## 📝 Description of the new feature

When the found text is in a method of a control on a form or class and you double-click to edit that method, in addition to opening an editor window for that method, also select the control. I'm working on a project where all the controls are named Text1, Text2, etc. so when I find some text in GoFish and double-click to edit it, I have no idea which control (other than the name) the code belongs to. Yes, I can open PEM Editor and search by name, but since the code to select an object already exists in PEM Editor, I thought it wouldn't be too difficult to repurpose it for this use as well.

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment] 2024-03-26 22:00
@DougHennig 

I'm kind of surprised by two things here:

1. That this has never been asked for before.
2. That it has never been considered as a reasonable expectation.

I wonder about drawbacks, if any ....

In any case, I do have a minor quibble with _I thought it wouldn't be too difficult_, as nothing having to do with PEMEditor code is straightforward,

This will be a good challenge.

**Comment by Jimrnelson** [comment] 2024-03-27 19:24
@DougHennig 

Doug --

I thought I'd fill you in on the direction I'm heading on this.  It turns out that there is already some easily modifiable code in GF that does a lot of what you ask.  

What happens now, fox VCXs only (not sure why SCXs don't work), is that if you have a match a property on an object and you double click on it, three things happen:

1. The VCX opens, as expected.
2. The control is selected (although there are exceptions, see below).
3. If PEM Editor is open, that control is selected in PEM Editor.

Step 2 above is limited in that the control to be selected must be at least partially visible, as VFP does not provide a function to select an object when editing.  What actually happens is that the cursor is placed in various places over where the object should be in order to try clicking on it.  IOW, this fails if the object is behind other objects or is on another page in a pageframe.

In any case, step 3 will show the correct control even if step 2 fails.

This is the best that I was able to do for VCXs and will be the model I will use for your request.  I assume that the issue with not working for SCXs is minor and easily correctable.

Hmmm, you might try this out now to see if there are any other wrinkles I should know about.

/ Jim

**Comment by Jimrnelson** [comment] 2024-03-28 22:39
This issue has been resolved in Version 7.0.20 - 2024-03-28 (#201)

**Comment by klepetox** [comment] 2024-03-29 07:11
Great functionality, I wouldn't have believed something like this could be done. But I have a question - every form with a selected element wants to save on exit, even if no changes have been made. I compared the forms binary before and after saving and they are completely different, but functional and intact. What changes are made that require saving?

**Comment by Jimrnelson** [comment] 2024-03-29 22:04
Doug --

This can be corrected by making a rather simple change in PEMEditor.  Since you have been maintaining it til now, I am hoping you can make this change. If that doesn't work for you, I'll take a crack at it. 

The idea is to pass an additional parameter to a few function calls so that one bit of code deep down can be avoided.

At the top we have this:

![image](https://github.com/VFPX/GoFish/assets/81179335/7bfb6f1f-1dd9-41cd-9e8e-6fbefc304e38)

which calls this:

![image](https://github.com/VFPX/GoFish/assets/81179335/44cb0fdc-dcd9-429c-889f-86e5330e9abc)

which calls this:

![image](https://github.com/VFPX/GoFish/assets/81179335/43d4198a-810a-40f7-b7ed-1e8f3137202a)

which calls this:

![image](https://github.com/VFPX/GoFish/assets/81179335/bc042204-9fbb-40f3-a20a-945ff54b5e11)

So the intent is to call SelectObject (in the first image) with a second parameter, tlWindowAlreadyActive and pass it all the way down so that the highlighted code in the last image may be skipped if it's true.

Note that doing so should not have any effect on any other existing code (always my intention).

**Comment by DougHennig** [comment] 2024-03-31 12:43
OK, those changes are done and pushed. I didn't make the top-level change (the call to SelectObject) but did make the changes to SelectObject, SetCurrentSelectedObject, and FocusOnControl.

**Comment by myearwood1** [comment] 2024-04-01 15:40
MaxFrame's search tool would open the method the search entry was in, but it did not access the object. I cannot use GoFish in vfp6. Good feature.

**Comment by myearwood1** [comment] 2024-04-01 16:30
Why in the pem_editor_utils.focusoncontrol are there 2 LOCAL commands? This works exactly the same:

LOCAL loTopOfForm as Object, laStartMouseObj[1], lcBaseClass, lcWindow, lcWindowName, llFound, llNoWindow

**Comment by Jimrnelson** [comment] 2024-04-02 14:19
> Why in the pem_editor_utils.focusoncontrol are there 2 LOCAL commands? This works exactly the same:
> 
> LOCAL loTopOfForm as Object, laStartMouseObj[1], lcBaseClass, lcWindow, lcWindowName, llFound, llNoWindow

Yes, that does work exactly the same.  

I put locals that are variables into a separate LOCAL statement.

**Comment by myearwood1** [comment] 2024-04-02 14:35
Why? Arbitrary habit? You are releasing something for others to use. Why should it not be as fast as you can make it especially when such a simple change saves many lines execution throughout the whole code base?

**Comment by Jimrnelson** [comment] 2024-04-03 13:55
Finally put to bed with Version 7.0.22 - 2024-04-03 #207

**Comment by klepetox** [comment] 2024-04-03 15:00
Jim, it is not still perfect. Two things:

1st - forms with empty caption (caption is variable and set in .init) doesn't select object. But if I start PEM editor, then object is selected. But I use PEM editor only sometimes, not always.

2nd - some forms sometimes still ask for saving after closing it without any changes made. I'm trying, but I cannot find any rule why.

**Comment by Jimrnelson** [comment] 2024-04-03 15:16
@klepetox 
@DougHennig 

> Jim, it is not still perfect. Two things:

Good points!  
 
> 1st - forms with empty caption (caption is variable and set in .init) doesn't select object. But if I start PEM editor, then object is selected. But I use PEM editor only sometimes, not always.

That makes sense.  The basic method for selecting the object (when SetFocus fails) is to mouseclick in 9 places around and inside the object.  To do so, you need the name of the window the object is in.  In an SCX, that window name is the caption.  Thus, if the form caption is empty, it fails.  (This can be corrected by temporarily changing the form caption any putting it back, but that causes the Save Changes dialog.).

PEM Editor _always_ temporarily changes the form caption, so it should always work.

> 
> 2nd - some forms sometimes still ask for saving after closing it without any changes made. I'm trying, but I cannot find any rule why.

That's what I am seeing as well.  The rule escapes me, but at least I have found the culprit  method (in PEMEditor)

**Comment by Jimrnelson** [comment] 2024-04-03 15:24
@klepetox @DougHennig 

The fixes for this are buried in PEMEditor.  I hope to get to it this weekend.

Doug, do I already have access to build PEMEditor ?

Oh, and I will make sure not to mark this issue as closed (again) until you guys have given thumbs up.

**Comment by DougHennig** [comment] 2024-04-03 17:40
@Jimrnelson Yes. See https://github.com/VFPX/PEMEditor/blob/master/.github/CONTRIBUTING.md for details (just the New Version section).

**Comment by Jimrnelson** [comment] 2024-04-09 21:44
@klepetox, @DougHennig 

OK, one more time.  My claim this time (after you get the latest updates from both GF and PEME):

In almost all cases, if you open a form or class from GF and then close it, you should not get the "Save Changes" dialog.

The exception would be for objects in a form where the form caption is empty. 

I will close this issue if I do not hear back from either of you in the next few days.

**Comment by klepetox** [comment] 2024-04-11 06:50
Some of my forms still require saving. But I have found one thing:

I find "thisform.release".

In the results I click on `frmFOdurd.cmdCancel` and the form opens, but then wants to save.

I searched for the cause and found a very dangerous thing. GoFish has made changes that when I save, it sets the `.Default` property wrong. I am attaching screenshots of the form opening from GoFish and from the command window.

I advocate that this new functionality should rather be removed (it's not that important and nobody has asked for it so far) or made it optional in the settings with the possibility to turn it off.

![1](https://github.com/VFPX/GoFish/assets/142881527/62105221-a9f1-4be3-92ea-6c0f9ead2758)


![2](https://github.com/VFPX/GoFish/assets/142881527/a518e3a8-977b-4212-9fbc-6e3682cf298d)

**Comment by Jimrnelson** [comment] 2024-04-11 12:56
@klepetox 
@DougHennig 

Wow, it's certainly mis-behaving now.

Apparently my attempted update to PEMEditor earlier this week did not work -- it SAYS it's the newer version, but the timestamp on PEMEditor.APP is clearly old.  I will correct that (once I figure out what I did wrong).

A separate issue is what you're seeing with the "Default" property.  That's pretty weird, as I can find nothing in my code to reference that property nor can I imagine what use there might have been to do so.  Before I release yet-another PEMEditor update, I'll try to dig into this.

Finally, you said this:

> I advocate that this new functionality should rather be removed (it's not that important and nobody has asked for it so far) or made it optional in the settings with the possibility to turn it off.

I assume that you mean this odd change to the handling of the "Default" property.  I agree, that should never happen.

First question on this one:  can you check to see whether the problem occurs both when PEMEDitor is open or when closed?

**Comment by klepetox** [comment] 2024-04-11 13:40
Open PEM Editor has no effect. It is the same. I'm attaching screenshots that might be helpful.

Result is for button `cmdCancel.Click`, but `cmdOK.Default` is damaged! You can see it immediately by the blue frame around the (Default) button. When opening the form from GoFish, the blue frame is not there.

![4](https://github.com/VFPX/GoFish/assets/142881527/1bf15cbe-753b-42a6-831a-ab18fda09b03)

------------------

![5](https://github.com/VFPX/GoFish/assets/142881527/9fe3a9e5-b09f-498d-bc06-b077cfb27cfd)

**Comment by klepetox** [comment] 2024-04-11 13:53
And I still see an interesting thing - the `cmdCancel` button (from GoFish) has a blue box as if .Default was set (it's not) but the .Cancel and .Default properties are set correctly. That's why maybe cmdOK.Default is being reconfigured (?).

**Comment by klepetox** [comment] 2024-04-11 14:48
I can already demonstrate this problem. Attached is a simple form with two buttons that have properties .Cancel and .Default set. Try running the form, there are instructions on how to simulate this exact problem.

[x.zip](https://github.com/VFPX/GoFish/files/14947710/x.zip)

**Comment by Jimrnelson** [comment] 2024-04-11 22:18
@klepetox, @DougHennig 

This issue has turned out to be more intricate than first imagined.

[1]  I believe that when I get the correct PEMEditor version out there, the odd behaviors with the DEFAULT setting reported by @klepetox will be corrected.  Probably Friday (California time) Friday.

[2]  I have found that there are circumstances where you get the "Save changes" message if you have PEMEditor open, but you don't get the message otherwise.  I cannot identify the circumstances other than to say that code is buried deep in PEMEditor and I don't want to muck with it.

[3] I wonder if this feature ("Select the control in which text is found when editing") should be made optional, with a default setting of "Yes".  I am now sure if that is what @klepetox was proposing in his earlier message.

**Comment by DougHennig** [comment] 2024-04-12 12:58
3. Likely a good idea.

**Comment by Jimrnelson** [comment] 2024-04-14 13:42
@DougHennig @myearwood1 @klepetox 

With this weekend's release of updates to PEMEditor and GF, I believe that this issue has finally been put to bed.

The difficulty with this request is that VFP does not provide a mechanism to select an object in a VCX or SCX that you are editing, nor does it provide a way to change which page in a pageframe is visible.  The behavior of a VCX/SCX being edited is very different from what we are accustomed to when actually running it.

The attempted solution is first to try SetFocus (which works, surprisingly enough, under some conditions) and if that fails to try clicking on eight border points and center of the control.  This works a high percentage of the time but is not infallible.  

If PEMEditor is open:
- The desired control should be selected there (while the Properties Window will show the control that matches what you see in the SCX/VCX being edited. )
- You might get the "Save Changes" dialog when closing the SCX/VCX even if you did not change anything.

**Comment by DougHennig** [comment] 2024-04-14 13:59
Sorry, @Jimrnelson, I just tried it in 7.0.25 and still get the save dialog whether PEM Editor is open or not.

**Comment by Jimrnelson** [comment] 2024-04-14 14:12
@DougHennig @myearwood1 

Doug -- Well, that's certainly strange.  Your description helps.  I will see if I can replicate.  Some behaviors here are very difficult to debug because the process of stepping through the code may cause things to work differently.

This may not be corrected (no promises, then) but will give it another try.

**Comment by Jimrnelson** [comment] 2024-04-14 14:29
@DougHennig @myearwood1 

I am not surprised to relate that I cannot replicate this problem.  

I had hoped that yesterday's update to PEME completely took care of this (GF uses a feature of PEME even when PEME is not open).

For now, I'm stumped.  Let me know if you can identify any other circumstances.

**Comment by klepetox** [comment] 2024-04-14 16:03
There is still a problem with forms with OK (.Default=.T.) and Cancel (.Cancel=.T.) buttons. If I search for "thisform.release", the Cancel button is selected and the OK button loses the .Default property. The form is thus corrupted because it does not respond to Enter or Ctrl+Enter. Subsequently, it is required to save the form.

**Comment by Jimrnelson** [comment] 2024-04-14 17:36
@klepetox, @DougHennig 

> There is still a problem with forms with OK (.Default=.T.) and Cancel (.Cancel=.T.) buttons. If I search for "thisform.release", the Cancel button is selected and the OK button loses the .Default property. The form is thus corrupted because it does not respond to Enter or Ctrl+Enter. Subsequently, it is required to save the form.

This is a problem with VFP itself and cannot be avoided.  

You can duplicate it yourself without using GF:

    Modify Form X.SCX
    ?ASelObj(laArray, 1)
    loControl = laArray[1]
    loControl.cmdCancel.SetFocus()

If you then check the cmdOK properties, you will see that the Default property has been changed to .F.

When you then close the form, you get the "Save Changes" message.     

This is certainly an unfortunate side effect.  It seems to happen if there is any button with Default = .T.

(Separately): I suspect that a questions about "Save Changes" would be a good first FAQ.

**Comment by klepetox** [comment] 2024-04-14 17:54
You're right, it is unbelievable, FoxPro itself is the source of this problem. Unfortunately, almost all my forms contain OK and Cancel buttons. That's why I can't use this functionality. So thank you for the option to turn it off.

**Comment by Jimrnelson** [comment] 2024-04-14 17:56
> You're right, it is unbelievable, FoxPro itself is the source of this problem. Unfortunately, almost all my forms contain OK and Cancel buttons. That's why I can't use this functionality. So thank you for the option to turn it off.

I ain't done yet.  Let's not give up so soon.

**Comment by klepetox** [comment] 2024-04-14 17:58
Thank you so much for your efforts, I really appreciate it

**Comment by Jimrnelson** [comment] 2024-04-14 17:58
> You're right, it is unbelievable, FoxPro itself is the source of this problem. Unfortunately, almost all my forms contain OK and Cancel buttons. That's why I can't use this functionality. So thank you for the option to turn it off.

My initial testing says this only happens if you are opening a command button AND the default command button is a sibling object.  If that's correct, it can be avoided.

**Comment by myearwood1** [comment] 2024-04-14 18:41
Make an aselobjX function that stores the Default property of the objects.
You can revert the change after the set focus.

**Comment by Jimrnelson** [comment] 2024-04-14 18:53
@myearwood1, @klepetox, @DougHennig 

> Make an aselobjX function that stores the Default property of the objects. You can revert the change after the set focus.

That's a good concept to start with.  It would require knowing which objects to look at (yes, it could certainly loop through ALL objects in the VCX/SCX); it might be sufficient to just look at sibling command buttons.

And it should only revert those that had been changed.

This would take care of the DEFAULT problem, although the "Save Changes" issue would still be there.

**Comment by myearwood1** [comment] 2024-04-14 19:38
Let it loop through all objects. In fact, build a cursor.  Run the function
a second time and use sql to find the siblings that changed.

**Comment by myearwood1** [comment] 2024-04-14 19:57
Name the function SelObj, not ASelObj. First parameter to be a cursor name.

**Comment by Jimrnelson** [comment] 2024-04-15 12:26
@DougHennig, @klepetox, @myearwood1 

> I just tried it in 7.0.25 and still get the save dialog whether PEM Editor is open or not. This happened with a form with a pageframe where the selected control is a command button in page 1 of the pageframe, if that helps. When I try it with a form where the selected control belongs to the form instead, then no save dialog.

Doug --

Any chance that that there is a commandbutton with Default = .T. on the form where the problem occurred?

**Comment by DougHennig** [comment] 2024-04-15 13:57
@Jimrnelson Yup, that's the culprit.

**Comment by myearwood1** [comment] 2024-04-15 14:26
Again, I advise you create a SelObj.prg that creates a cursor. It is better
than writing looping code to scan the array looking for that changed
property.

**Comment by Jimrnelson** [comment] 2024-04-15 14:51
@DougHennig @myearwood1 @klepetox

> Again, I advise you create a SelObj.prg that creates a cursor. It is better than writing looping code to scan the array looking for that changed property.

No, I won't be using a cursor, for a number of reasons:

1. The code is already working (and uses neither arrays nor cursors)
2. This has to do with objects -- cursors and objects do not mix well.
3. There can only be one object with DEFAULT = TRUE, so all that is needed is to know that object.

In the abstract, this is very simple:

Before Selection:  Find the object (if any) that has DEFAULT = TRUE

After Selection: If that object now has DEFAULT = FALSE, set it back.

**Comment by myearwood1** [comment] 2024-04-15 19:04
So one looping construct to find the offending object which you can reuse
after? No problem. Cursors and objects can work very well together. Hide
the cursor in the private data session of an object based on the session
class. The named array has the same opportunity to be affected as does a
cursor.

**Comment by Jimrnelson** [comment] 2024-04-15 19:21
@DougHennig, @myearwood1, @klepetox

> So one looping construct to find the offending object which you can reuse after? No problem. Cursors and objects can work very well together. Hide the cursor in the private data session of an object based on the session class. The named array has the same opportunity to be affected as does a cursor.

First if all, as already stated, the code is already working and uses _neither arrays nor cursors._

Second of all, the procedure to accomplish this is self-contained, straightforward and brief (only 12 actual lines of code).

**Comment by Jimrnelson** [comment] 2024-04-15 23:27
@DougHennig, @myearwood1, @klepetox

Version 7.0.26 - 2024-04-15 released

- Dramatic optimization of RegEx searching -- as much as seven times faster.
- Bug fixes:
    - Problem when editing (double-clicking a row) could cause the Default property on a commandbutton to be changed to FALSE.
    - When browsing binary file (VCX/SCX) as a table
    - When right-clicking on column header.
    - Search history was not being saved if no matches found.

**Comment by Jimrnelson** [comment] 2024-04-15 23:28
@DougHennig, @myearwood1, @klepetox

Once again, I am claiming that this issue is resolved, although I am not closing it.

Implemented as follows:
- If there is a command button on the form/class being edited that has DEFAULT = True and that value gets changed to False by GF, then the value will be set back to True.
- This will result in the erroneous "Save Changes" message, but that cannot be avoided.

**Comment by DougHennig** [comment] 2024-04-16 14:28
So far so good in my testing. I am seeing the save dialog only under those conditions.

**Comment by klepetox** [comment] 2024-04-16 15:16
I have found another strange error.
Form Test.scx contains cmd1 and cmd2 buttons. Both of them contains "Go Bottom" in .Click event. Try to find "go bottom" in GF and in the result grid click on **frmTest.cmd2**. There's an error in my environment, screenshots are attached. A clue might be that cmd2 has the last .TabIndex.

[test.zip](https://github.com/VFPX/GoFish/files/14998969/test.zip)

![2](https://github.com/VFPX/GoFish/assets/142881527/8ce22de2-ba7e-42e9-bf17-6451aee471e8)

![1](https://github.com/VFPX/GoFish/assets/142881527/03e03056-0e13-421f-a1ca-95673a87b2cb)

**Comment by Jimrnelson** [comment] 2024-04-16 17:26
@klepetox 

I don't think those two errors are related to GF.

The first (FoxCode) has to do with a problem with your FoxCode file and be replicated outside of GF.

The second ("Incorrect function") is a new one to me.

**Comment by klepetox** [comment] 2024-04-17 07:52
I tried GF 6 and there is no such error. Can I download the first versions of GF 7 somewhere to see from which version the error occurs? The file `foxuser.dbf` is readable and correct. Somebody reported the same error yesterday in #218.

**Comment by Jimrnelson** [comment] 2024-04-18 17:50
@DougHennig, @myearwood1, @klepetox

There's been a lot of discussion on this topic, but I believe all issues have been addressed.

If there's anything I missed, it should go into a new issue.

**Closed by Jimrnelson** 2024-04-18 17:50 UTC
