### ISSUE TITLE
Filter Builder errors when filter string is equal sign

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#8] opened 2022-09-23 19:01 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Do a search. As long as the results include some lines with equal signs, any search will do
2. Click Filter
3. On the Code page of the Filter Builder, specify = Within Same Statement
4. Click Apply

### ✔️ Expected result

Results should be limited to lines containing equal sign (which they are) and Code View pane should show those code blocks.

### ❌ Actual result

Error message (see screenshot 1). Code View pane shows funky XML instead of code (see screenshot 2)

## 📷 Screenshots
![goFishFilterError](https://user-images.githubusercontent.com/30271640/192038971-6d1e6aeb-be80-4855-ad91-5b019b4e0f3e.jpg)
![GoFishFilterErrorCodeView](https://user-images.githubusercontent.com/30271640/192038989-dbd35205-afba-47f5-abbd-772730a548e5.jpg)

**Comment by DougHennig** [comment] 2022-10-15 14:43
If you figure out what change to make, I'll implement it.

**Comment by lscheffler** [comment] 2023-03-18 12:59
@TamarEGranor I can not reproduce the error on V6.
The expression "="="='vfp.." is false. See #9.  

---
If you find a way to reproduce the error let me know, else we can close this, the filter problem will double #9.

**Comment by lscheffler** [comment] 2023-04-15 15:36
@TamarEGranor Does this problem still exist? I can't reproduce.

**Comment by TamarEGranor** [comment] 2023-04-17 13:51
Yes, I can still reproduce it. Wondering if my step 3 is unclear. What I'm saying is that on the Code page of the Filter Builder, in the box for Within Same Statement, put just an equal sign, as in the image here.
![filterbuilderequal](https://user-images.githubusercontent.com/30271640/232504097-4a69ba7c-0f40-4f93-b00d-afbffed1905d.jpg)

At first, I just see the weird XML, but when I click on a different item, I get the error shown in the original post.

**Comment by Jimrnelson** [comment] 2023-04-17 14:01
@TamarEGranor 

Yes, I can reproduce this.  

Not surprising, really, as it's trying to highlight matches in the code view page and the '=' sign wreaks havoc with the HTML.  There are probably other special characters that could cause this failure as well.

**Comment by lscheffler** [comment] 2023-04-17 16:34
Ah, now I see it.    
This is the HTML generation replacing any **=** with **`<span id="matchword" class="matchword">=</span>`**, even if the equal sign is in html tag or JS script. What ends up very stupid. Try ", /, < or >; any html expression ("span", "br", "class" [**class!**] ); for similar fun.  Kind of a post-processor. Not my special place, this might take a while.

**Comment by Jimrnelson** [comment] 2023-04-17 16:41
If you can identify the cases in which this fails, I suggest that we can live without the HTML highlighting the filter expression.

In other words, if you know it's going to fail, don't even try to fix it.

**Comment by Jimrnelson** [comment] 2023-04-17 16:48
Here's an interesting tidbit:

While the HTML fails if you just enter a single  = , the filter works and the HTML doesn't fail  if you use wildcards ...  *=*

It seems like the highlighting of the filter expression only works if there are no wildcards used (which makes sense to me, actually)

**Comment by lscheffler** [comment] 2023-04-17 16:53
Hard to say, since any HTML special char, tag, css class-name, css expression and any JS keyword might create havoc. List is simple to long.
It look like it's more easy to change the order of processing, but it needs to be looked up too.


To the wildcards, I have no idea how this works, but in `<span id="blabla" class="blub">=</span>`, there are at least 3 matches for \*=\* :)

**Comment by lscheffler** [comment] 2023-04-19 20:31
It is as fancy as I thought. Typical hen-egg problem.
- it's impossible to run this first, this would break syntax color etc.
- simple search and replace will harm HTML (...)
- the search as it is will fail for, as example `<`, this is translated to `&lt;`- so it will ONLY harm the HTML    

It would need a special run:
- transform search for stuff like `<` to `&lt;`
- parse out anything inside a < >   (at least it looks well formated)
This need a complete new parser. Or just turning this colour of.

**Comment by lscheffler** [comment] 2023-04-20 17:21
I found a way to work this with regexp. At least partial. My problems
- I need DotNet regexp
- That means wwDotNetBridge
- Since DotNet regexp does not feature conditional replace, I can only use it for match, the replace need to be in a loop and done by VFP

It also need to fiddle with the pattern to escape regexp signs and HTML chars, but this is minor. (but not fast)

What do think about this? Is this worth the effort?

**Comment by Jimrnelson** [comment] 2023-04-20 18:51
@TamarEGranor @lscheffler 

For you to make this work you would have to include all the necessary files in GoFish.APP, or create a new Thor project to deliver them and have GF use that project if it were installed.

I do not think this is worth the effort.  I suggest that this is a relatively minor problem that is worth solving if it can be done with a relatively minor investment of time.

If it were me, I would see if I could identify the few most likely identifiable cases in which the current code fails and simply choose not to highlight in those cases.

**Comment by lscheffler** [comment] 2023-04-20 19:24
The problem is that a simple _top_ or _class_ will fail. Just rightclick  the browser window in GoFish, open the source. All inside \< \> and \< \> itself. And then the HTML chars are transformed anyway.

It would need to add wwDotNetBridge to the project, no big deal - that was the issue in Thor. The rest is more or less an easy task (https://xkcd.com/208/), just not very fast since one must loop through all the matches - sadly including the tags. If speed is really an issue - well it could be done in DotNet as a whole instead of several (on odd patterns hundreds) calls. The question is more like - is there so much use of this feature?
I do not use it.

**Comment by Jimrnelson** [comment] 2023-04-20 19:28
When you say "this feature" -- what specifically are you referring to?  Showing the Code Window?  Searching for =  ?

**Comment by lscheffler** [comment] 2023-04-20 19:38
That what the issue is about. A filter over a search, and in special to highlight that filter expression in code window. https://github.com/VFPX/GoFish/issues/8#issuecomment-1511393624

**Comment by Jimrnelson** [comment] 2023-04-20 20:04
I use the filter expression "within the same statement" quite often.    Highlighting the filter search term in these cases is not of much value to me.

I use the filter expression "within the same procedure" very rarely.  In these cases, I find that highlighting the filter search term is quite valuable, as it might be some distance from the original line of code.

I am not much concerned about the rare cases where the HTML currently fails.  If you can't prevent it from failing, perhaps an button near the HTML that says "Fix HTML" and does so by ignoring highlighting.  Now that I've that, I think that's the most straightforward solution of all.

BTW (and maybe you want me to add this as a separate issue) ... it would be real nice if the filter search term were highlighted in a different color.

**Comment by lscheffler** [comment] 2023-04-20 20:27
More or less the work is done - the big task is to create the pattern, the rest is for a code monkey. I was able to reduce the (necessary) superfluous matches by a huge number last hour. Nice little thing:
```
*for a given search filter lcpattern:
pattern = "\<[^\>]*?(?:"+lcpattern+")+?.*?\>|("+lcpattern+")"
```
There are minor issues with the regexp options, but I hope to learn this.

---
For the colour(s), please create a separate issue. I had the general idea as I was doing colour picker for the form/grid, but it's a different approach, since it needs to alter the CSS file. A lot of additional work to handle this, it might even need a different way to handle the whole CSS file.

**Comment by Jimrnelson** [comment] 2023-04-20 20:30
In which case you are echoing Matt's words, which were that is was not worth the investment

**Comment by lscheffler** [comment] 2023-04-21 05:35
Introducing a new CSS class for this replacement is no deal. So, just go ahead with a new issue.   

The simple solution would be to allow to edit an external copy of the CSS. (Edit with some text editor, external to GoFish). This would do.

**Closed** 2023-05-09 13:44 UTC
Labels: question
