### ISSUE TITLE
Status bar is not restored on GoFish deactivate

### ISSUE THREAD

**Issue by nmpetkov** [VFPX/GoFish#77] opened 2023-03-29 16:22 UTC
## ℹ Computer information

- VFP version: VFP9 SP2
- GoFish version: 6.0.009
- Last GoFish version w/o bug (if available): 5.1

## 📝 Provide detailed reproduction steps (if any)

After using GoFish and subsequently opening a prg file, the line number is no longer displayed on the status bar (previously in the VFP options it was specified to be displayed). I assume because Gofish uses the status bar - I see `Done` there when activating GoFish. 

### ✔️ Expected result
After deactivation GoFish, the status bar window to return to its previous state and show the line number of open PRG files.

I managed to find solutiton by editing

`gf_resultsform` class, Deactivate method, at the very end place:

`SET MESSAGE TO`

Not sure if this is the best solution, but it works.

**Comment by lscheffler** [comment] 2023-04-01 12:42
I see what you mean - only I see not what turns this off - and I will not touch on something that was not on.

So what I need is:
1. gather the settings on startup
2. (re)set on GF_FilterForm  (De)Activate

**Comment by myearwood1** [comment] 2023-07-06 16:39
Unbelievable. This is known best practice.

As GoFish starts, capture SET("MESSAGE",1) to someplace. As GoFish exits, SET MESSAGE TO that value.

I demonstrated it by opening the Changelog_Thor.txt, enabling the Show line/column position by right-clicking on the window and selecting Properties. I stored SET("MESSAGE",1) to a public variable. When GoFish runs, my status bar message was changed to "Done". It doesn't matter what caused that. Then after I exit GoFish, I restored SET MESSAGE from my public variable and re-opened the Changelog_Thor.txt and the row/col position was displayed.

You do not follow best practices. You do not respect the user's environment. So typical.

**Comment by myearwood1** [comment] 2023-11-23 19:44
In SetupEnvironment in gofish.prg, add this as the last 

		ADDPROPERTY(m.loGoFish, "cStatusBarMessage",SET("MESSAGE",1))

After the EndIf of If Version(2) = 0

SET MESSAGE TO _Screen._GoFish.cStatusBarMessage

Easy as that.

**Comment by Jimrnelson** [comment] 2024-03-09 14:49
@nmpetkov 
@klepetox 

This issue has been corrected in Version 7, released 2024-03-08.

Note, however, that the browser used for the Code View pane will write to the status bar (something out of our control).

Thus, after you open method code, if you mouse over the Code View pane (not even transferring focus to GoFish form), the status bar says "Done" and line/column numbers are no longer displayed.  I don't believe that this oddity is correctable.

This issue appears to be a duplicate of #153

**Closed by Jimrnelson** 2024-03-09 14:49 UTC

**Comment by Jimrnelson** [comment] 2024-07-27 13:32
@nmpetkov
@klepetox

I just stumbled across this in my own work and noticed that after using GF the status bar occasionally goes blank and stays that way.  Are you still experiencing this?

If so, do you have a recommended way to fix it?  The only thing that I have tried successfully is this:

    Set status bar off
    Set status bar on

**Comment by klepetox** [comment] 2024-07-27 13:42
I've never noticed it since it was fixed, even now everything seems to be fine, but I'll keep an eye on it.

**Comment by myearwood1** [comment] 2024-07-27 15:58
> @nmpetkov
> @klepetox
> 
> I just stumbled across this in my own work and noticed that after using GF the status bar occasionally goes blank and stays that way.  Are you still experiencing this?
> 
> If so, do you have a recommended way to fix it?  The only thing that I have tried successfully is this:
> 
>     Set status bar off
>     Set status bar on
> 

Is gofish not in a private data session? It should not participate in the developer's data environment. I think the status bar setting would be protected by the data session. You should capture the status bar setting when gofish starts to a property of gofish. When gofish gets focus set the status bar like that. When gofish loses focus, set it back as the developer had it.

**Comment by Jimrnelson** [comment] 2024-07-27 16:15
@nmpetkov
@klepetox
@myearwood1 

GF is in a private data sessions, but status bar settings are not related to data session.

Yes, it seems that it's enough to just do `set status bar on` (if it was originally on) and that works fine.

**Comment by myearwood1** [comment] 2024-07-29 18:46
@Jimrnelson Just a point related to this. My system takes 42 seconds to do a build exe with status bar on. With status bar off, the wait window shows the files and the time to build increases to 72 seconds.
