### ISSUE TITLE
Scope setting on open

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/GoFish#172] opened 2024-03-07 19:14 UTC
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_
Add an option to the 'Preferences' tab: Set to current project on open (or similar)
When GoFish opens, the scope is set to the <<active project>>.

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment] 2024-03-09 16:16
This feature has been implemented in Version 7, released 2024-03-08 with the new Search Mode combobox, which is a permanent setting.

![image](https://github.com/VFPX/GoFish/assets/81179335/0a33083e-da35-4502-bf6a-cb4bb6c5746b)

This issue appears to be a duplicate of #137.

**Closed by Jimrnelson** 2024-03-09 16:16 UTC
