### ISSUE TITLE
Replacements in menus stopped working

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#283] opened 2024-08-17 12:08 UTC
## ℹ Computer information
- GoFish version: 7.1.19

## 📝 Provide detailed reproduction steps (if any)
**Replacing** text in menus is broken. Error pops up for each line.

It is not anywhere in GoFish configuration, I have tried clean GoFish and it is the same.

**Searching** itself is correct.

## 📷 Screenshots

![1](https://github.com/user-attachments/assets/ec29e011-9ac5-4254-9b12-bfc1b730b65f)

**Comment by Jimrnelson** [comment] 2024-08-19 22:21
@klepetox 

I have been able to reproduce this error and have learned it is a direct result of the change in display in the Code View pane to matches in MNXs. 

I don't have any good feeling yet on how hard this will be to fix.

BTW, this is a great demonstration of the work Matt Slay build into the GF search engine to ensure that replacements are done safely (even though the error message is inaccurate in this case).

**Comment by Jimrnelson** [comment] 2024-08-21 15:42
Fixed in Version 7.1.20 - 2024-08-21

**Comment by klepetox** [comment] 2024-08-21 16:10
Už je to správně. Ale po nahrazení se objeví jiné chybové hlášení

**Comment by klepetox** [comment] 2024-08-21 16:24
It's already correct, but after replacement another error message appears:

`Error creating backup of file.    [File: c:\fox\#ukzuz\ukzuz\hsp\!project\menu\mainmnu.mnx]    [Result Id: 1017]`

I made backup manually and switched of option "Backup source files when performing Replace operations".

Forms and programs are backup correctly.

**Comment by Jimrnelson** [comment] 2024-08-21 18:05
@klepetox 

Unfortunately, there's not really any information there about the problem (which hasn't happened for me).

Please try the latest version 7.20.1, which should provide at least some more of an idea of what's going wrong.  My guess is that it has to do with exclusive access somehow.

**Comment by klepetox** [comment] 2024-08-21 18:26
I have tried version 7.1.20.1 and this is the result:

`Source file has changed since original search:    [File: c:\fox\#ukzuz\ukzuz\hsp\!project\menu\mainmnu.mnx]    [Result Id: 32]`

Nothing is replaced and when I double click in the grid, blank program window is displayed and to Foxpro goes down completely, but not everytime. The version 7.1.20 is ok except of mention backup.

**Comment by Jimrnelson** [comment] 2024-08-21 18:44
@klepetox 

First of all, the only change in 7.20.1 is that the error message is more explicit, as it includes `loException.Message`.

Now, what you are reporting here (`"Source file has changed"`) is a different message altogether than the first (`"Error creating backup of file"`), so something else is going on now.

Are you doing a fresh search each time?

**Comment by klepetox** [comment] 2024-08-21 18:50
Tomorrow I'll try to test it in detail, it's late in our country and we're going to bed, so tomorrow... Thanks for the effort!

**Comment by Jimrnelson** [comment] 2024-08-21 18:52
Yeah, I was surprised you were answering at all.

**Comment by klepetox** [comment] 2024-08-22 05:30
See error message - mpx?
![1](https://github.com/user-attachments/assets/c4da7ef2-cd2e-4621-bf31-a582c762208b)

Match Type "Resname" shows procedure from another menu in code pane, when I double click on it, quite another procedure is open.
![2](https://github.com/user-attachments/assets/a55ad877-af44-4f88-b03d-745cc47888de)

**Comment by Jimrnelson** [comment] 2024-08-22 12:16
RE: first image (with error message).

Am I correct that you have MNX and MNT files but not the associated MPR and MPX files?  (GF is trying to back up all four and fails if they don't all exist).

RE: second image.

Please attach all the files from this menu so that I can try to reproduce this.  For starters, I can't imagine where Match Type <Resname> could come from.

**Comment by klepetox** [comment] 2024-08-22 12:26
MPX - I have never saw file with this extension, I know it is compiled MPR, but project create only MPR, not MPX.

Which files from menu do you mean? Do you mean complete MNX + MNT? If so, I will send you by e-mail, not here.

**Comment by klepetox** [comment] 2024-08-22 12:37
The menu is here, I will delete it in a while, I don't want the menu be shared in public.
[Menu.zip](https://github.com/user-attachments/files/16710640/Menu.zip)
In example try to find "use " (with space), whole words, match case.

**Comment by Jimrnelson** [comment] 2024-08-22 12:48
Wow, `ResName` is not a field name that GF recognizes and it certainly does not handle it correctly!

**Comment by Jimrnelson** [comment] 2024-08-23 00:34
See Version 7.1.21- 2024-08-22

- Bug fixes:
    - Matches in field `ResName` in MNX files were not being handled correctly. (#283)
    - Backups of MNXs during replacements were failing if either 'MPR' or 'MPX' files did not exist (#283)

**Comment by klepetox** [comment] 2024-08-23 05:40
Menu search is now correct, Resname works correctly too.

But I cannot replace, no checkboxes at all.

![1](https://github.com/user-attachments/assets/125a88e9-a08d-42e0-a121-d886b59293e6)

Further, when I click on the results grid, the menu is open correctly, but the program window does not open as before.

![3](https://github.com/user-attachments/assets/10b0b2f0-c1fe-4c00-87ec-c90c0b861f06)

**Comment by Jimrnelson** [comment] 2024-08-23 11:48
See Version 7.1.21- 2024-08-23

**Comment by klepetox** [comment] 2024-08-23 12:09
Looks like everything is fine now.

**Comment by klepetox** [comment] 2024-10-04 14:28
There's a problem with replacements in menu again. I click "Replace view" button, confirm "Check all" - and sometimes, but not always (???) GoFish shows this error (before replacement):

![1](https://github.com/user-attachments/assets/752663ba-3d5e-4f0a-a229-131a9cf5a2ca)

If I do replace (even with no error before), errors occurs again and some lines are still ticked:

![2](https://github.com/user-attachments/assets/b157afc2-bb2a-4edc-bed1-a442d1a63b83)

But what is most interesting - all changes are done correctly in all rows! When I search "loop" again (match case) nothing is found. I checked the menu manually and everything is OK, replaced without any damage.

**Comment by Jimrnelson** [comment] 2024-10-04 16:53
@klepetox 

Well, this will be an interesting one to track down, since it seems to occur sporadically and seem to make replacements that it says it could not do.

Can you attach the files and provide directions so that I can see what's going on?  If you feel uncomfortable about sharing them here, you could send them to my email JimRNelson@gmail.com.

**Comment by Jimrnelson** [comment] 2024-10-04 21:37
See if Version 7.1.28 - 2024-10-04 takes care of this problem.

**Closed by Jimrnelson** 2024-10-04 21:37 UTC

**Comment by klepetox** [comment] 2024-10-05 07:18
I have tried version 7.1.28 and there's no problem any more.
