### ISSUE TITLE
Scope setting on instantiation

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/GoFish#137] opened 2023-10-13 13:44 UTC
## 📝 Provide a description of the new feature
Currently, when GoFish opens, the search scope is set to the last used project.
Is there a way / Can we have an option for "Open with active project"?
_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment] 2023-10-13 13:46
@BobWilkes 

The dropdown list for scope has an option "Active Project", which does what you are asking.

**Comment by BobWilkes** [comment] 2023-10-13 13:48
Yes, that's what I use now.
But I want the currently active project to be inserted atomatically.


------ Original Message ------
From "Jimrnelson" ***@***.***>
To "VFPX/GoFish" ***@***.***>
Cc "BobWilkes" ***@***.***>; "Mention" 
***@***.***>
Date 10/13/2023 9:46:43 AM
Subject Re: [VFPX/GoFish] Scope setting on instantiation (Issue #137)

**Comment by Jimrnelson** [comment] 2023-10-13 13:57
@BobWilkes 

Well, son of a gun, that is a feature that has disappeared!  It USED to work that way, I have no idea when it stopped working that way.

That is exactly the reason that that option is there.

**Comment by BobWilkes** [comment] 2023-10-13 13:59
Rhetorical ?
     And who has the magic wand to make it reappear?


------ Original Message ------
From "Jimrnelson" ***@***.***>
To "VFPX/GoFish" ***@***.***>
Cc "BobWilkes" ***@***.***>; "Mention" 
***@***.***>
Date 10/13/2023 9:57:43 AM
Subject Re: [VFPX/GoFish] Scope setting on instantiation (Issue #137)

**Comment by Jimrnelson** [comment] 2023-10-14 11:47
@BobWilkes 

I see from the following code in GF that the setting for "Active Project" is now treated  as a temporary selection.

![image](https://github.com/VFPX/GoFish/assets/81179335/34f7eb7c-b624-4b76-ac6c-704d8907fd18)

I view this as an unfortunate decision. The intent of that option was to allow GF to always search the active project when opened and not merely as as one time selection.  It is annoying that this functionality has been removed.

**Comment by Jimrnelson** [comment] 2024-03-09 16:15
This feature has been implemented in Version 7, released 2024-03-08 with the new Search Mode combobox, which is a permanent setting.

![image](https://github.com/VFPX/GoFish/assets/81179335/0a33083e-da35-4502-bf6a-cb4bb6c5746b)

This issue appears to be a duplicate of #172.

**Closed by Jimrnelson** 2024-03-09 16:15 UTC
