### ISSUE TITLE
file access denied.

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#182] opened 2024-03-15 16:05 UTC
## ℹ Computer information

- VFP version: 9
- GoFish version: 6.2

## 📝 Provide detailed reproduction steps (if any)

1. …Have a .prg file open
2. …Do a search that includes that .prg
3. …Program crashes with file access denied

### ✔️ Expected result

Program should give the user the option to close the .prg and retry.

### ❌ Actual result

Program crashes in gofishsearchengine.searchinfilename

**Comment by Jimrnelson** [comment] 2024-03-15 21:02
I have been unable to reproduce this error in the latest version (7.0.14 - 2024-03-15).

This is not surprising as there has been some refactoring that may have resolved the problem.

I am closing this issue but if it recurs in version 7, please open a new one and include screenshots of the call stack and locals list from the debugger.

**Closed by Jimrnelson** 2024-03-15 21:02 UTC
Labels: bug
