### ISSUE TITLE
Some searches produce OLE error code 0x800a139c: Unknown COM status code

### ISSUE THREAD

**Issue by nmpetkov** [VFPX/GoFish#68] opened 2023-03-17 16:24 UTC
## ℹ Computer information

- VFP version: VFP 9 SP2
- GoFish version: 6.0.007
- Last GoFish version w/o bug (if available): 5.1

## 📝 Provide detailed reproduction steps (if any)

Some searches produce an error:
`OLE error code 0x800a139c: Unknown COM status code.`

To reproduce search for:
`OpenPath(`

These are usually expressions that look like part of method names.
Guessing, but not sure, macro substitution is being used somewhere.

## 📷 Screenshots

![2023-03-17 18 12 59](https://user-images.githubusercontent.com/628801/225962020-18a04444-977a-4962-9117-8832fc697fd6.jpg)

**Comment by Jimrnelson** [comment] 2023-03-17 19:47
I am not able to reproduce this error.

Am guessing here -- are you searching using regular expressions?

Also, can you suspend the error and show the execution stack?

**Comment by nmpetkov** [comment] 2023-03-17 20:00
After reproduce again the error (I get many times to the moment), I see it you get if you HAVE results, the results table is not empty.
Here is call stack:

![image](https://user-images.githubusercontent.com/628801/226019324-3d1d9b37-1080-4110-a2af-b38d6be92174.png)

**Comment by Jimrnelson** [comment] 2023-03-17 20:39
As I guessed, you're using regular expressions.  As I noted in another message, regular expressions are about 5 times slower that the other search alternatives, so the suggestion is to use them only if you really want to use a regular expression.

The search expression you entered, **OpenPath(**, contains a special character (the left parenthesis) used in regexp and needs a closing right parenthesis to be valid.  But these characters have special meaning in RegExp.  If that is the text you really want to look for, don't use regular expressions.

That being said, GF tries to validate the search expression before getting going.  When I try it, I get this:

![image](https://user-images.githubusercontent.com/81179335/226035913-82d9d05d-7200-4e32-9d1f-b4d6d3ab72e2.png)

So, the question behind all this is why this validation works correctly for me and nor for you.  That I cannot answer.

**Comment by nmpetkov** [comment] 2023-03-17 20:44
There is no  regular expressions, just plane search.
The error occurs not during the search, but afterwards, when displaying the search result.
Please look at the call stack abouve in the provided image.

**Comment by Jimrnelson** [comment] 2023-03-17 20:50
> There is no regular expressions, just plane search. The error occurs not during the search, but afterwards, when displaying the search result. Please look at the call stack abouve in the provided image.

Ah, you are correct, my bad.

So the problem occurs when it is trying to display the context pane that shows that line and surrounding lines (for most, this line appears under the grid.)

RegExp is used, apparently, to generate the HTML code that appears there, which includes highlighting the match line.  (Yes, that sounds like another issue, doesn't it.)

Am guessing that a rather simple fix, a Try/Catch in the correct place, would prevent the error (as well as the hoped for highlighting.)

**Comment by nmpetkov** [comment] 2023-03-17 20:53
> Am guessing that a rather simple fix, a Try/Catch in the correct place, would prevent the error (as well as the hoped for highlighting.)

I also think that would solve the problem

**Comment by Jimrnelson** [comment] 2023-03-17 20:56
Also --

I have not upgraded to version 6 yet.  I do not see this problem in version 5.

**Comment by lscheffler** [comment] 2023-03-17 20:56
@Jimrnelson The expression `BlaBla(` as regexp runs fine, gets tero results and an error-message complaining about the wrong pattern afterwards, but does not fail unexpected.   

@nmpetkov As I see from the call stack, the build of the HTML browser output fails. Does any other search run, or can you display a restored search result at all?

Please post the value of lcRegEx.

@Jimrnelson I guess the problem is different. The engine uses regexp internally to create the HTML, try to replace the pattern
`blabla(` and fails because the bracket is not escaped. So in GoFishSearchEngine.RegExReplace, **if the search runs without regexp**, the pattern must be expected as as literal string and signs special for regexp must be escaped out. (Tanks to the other issue I have my brain turne on for regexp. :) )

**Comment by lscheffler** [comment] 2023-03-17 21:13
@nmpetkov To bypass the problem try:   
Activate regexp. Use `OpenPath\(` as search string. This will slow down GoFish  by an order of magnitude, but at least should display your result. Untested, I'm 16h on the keyboard and quit for today.

**Comment by nmpetkov** [comment] 2023-03-17 21:14
> I have not upgraded to version 6 yet. I do not see this problem in version 5.

As I stated when opening the issue, it is error in version 6 only.

**Comment by nmpetkov** [comment] 2023-03-17 21:16
@lscheffler @Jimrnelson 
To reproduce the error in GoFish 6, open one of your projects and temporarily write somewhere in it
`OpenPath(`
and save the file (later of course remove it when you've seen the error :-)
Then search
`OpenPath(`
and see the error.

**Comment by lscheffler** [comment] 2023-03-17 21:23
@nmpetkov Thanks, I see where it happens, and it should happen to any search like `somechars(` or `somechars[` or similar right now, because the pattern fails. The question is why does it run in older versions, or in other words, what have I removed unintended. Since I have not touched this method it remains a  bit of a riddle. But nothing a compare tool could not solve. :)

**Comment by lscheffler** [comment] 2023-03-18 06:23
@nmpetkov I found the error, I found the change - only I do not see why. I need to think a bit around this.

**Closed** 2023-03-18 18:25 UTC

**Comment by nmpetkov** [comment] 2023-03-18 20:00
Works in 6.0.008. Nice!
