### ISSUE TITLE
GoFish on 4k monitors

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#155] opened 2023-12-26 11:41 UTC
I use GoFish on 4k display with all 4k advantages, my GoFish form is large. By default, objects above grid are anchoring. This causes too much mouse moving and loss of clarity. I suggest very simple solution. Add a new option in the settings "Do not anchore objects above grid".  Try to look at both pictures in full resolution.

![GoFish-default](https://github.com/VFPX/GoFish/assets/142881527/c6051156-b4c7-4e6a-b96a-ac0dd2d6d5c3)

![GoFish-anchor0](https://github.com/VFPX/GoFish/assets/142881527/8836f9b2-356d-41cb-9498-8da5fc59bf01)

**Comment by lscheffler** [comment] 2023-12-26 12:17
@klepetox This looks really ugly. The first and fast help: Do not move to mouse to click the fish. Just hit \<Enter>.

There is some sense in increasing the search and scope fields, but not that much. Only limiting to a good range is a problem.

Check old issue #105 that deals with a similar problem.
It looks like for small stuff the Anchor solution is better, but not for bigger screens.

I see no good solution right now, but I will have a look at it.

**Comment by Jimrnelson** [comment] 2024-03-09 16:07
@klepetox 

This feature from Version 5 has been re-implemented in Version 7, released 2024-03-08.

It works like this:

- If the form width of GF is 1500 or less, the controls atop the form respond normally to their Anchor properties.
- If the form width of GF is more than 1500, the controls atop the form respond as if the form width is 1500.

This feature appears to be a duplicate of #155.

**Closed by Jimrnelson** 2024-03-09 16:07 UTC
