### ISSUE TITLE
RegEx file search does not appear to be updating the progressbar. 

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#209] opened 2024-04-04 22:44 UTC
## ℹ Computer information

- VFP version: 9
- GoFish version: 7.0.16

## 📝 Provide detailed reproduction steps (if any)

1. …Doing a search through a massive collection of code that grew like weeds over the years - you know, the kind nobody claims to write or have seen - with this regex \b(REPORT|REPO)\s+FORM\s+(?!(?:'[^']*'|"[^"]*")\s*)[^'"\s]+(?:\s+[^'"\s]+)*\b
2. …the "searching..." progress bar does not update.
3. …the escape key does not respond

### ✔️ Expected result

_What is the expected result of the above steps?_
The progress bar should update as GoFish passes through the files and the escape key should terminate.

### ❌ Actual result

_What is the actual result of the above steps?_

![image](https://github.com/VFPX/GoFish/assets/5750619/eba6ede8-401f-4a00-9b45-f4d123460858)

## 📷 Debugging Info
Please add screenshots of
- Error Message
- Windows from the debugger
     - Trace window
     - Locals window
     - Call stack window

## 📷 Screenshots

_Are there any other useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by myearwood1** [comment] 2024-04-04 22:50
It did eventually respond to the escape key. It ran for 959 seconds.
![image](https://github.com/VFPX/GoFish/assets/5750619/61235287-791f-4e4d-ba66-75653c83b375)

**Comment by myearwood1** [comment] 2024-04-04 22:53
Just to put things in perspective, I have all source on my local machine with an SSD and the application is enormous. No weeding was ever done. No modularity seems to have been attempted. 5 and 6 copies of code with minor differences.... I'm leaving it to run that regex. Will show the result in the morning.

**Comment by myearwood1** [comment] 2024-04-05 14:06
![image](https://github.com/VFPX/GoFish/assets/5750619/962c86b4-a035-4d3e-a872-d02b8541678a)

**Comment by myearwood1** [comment] 2024-04-05 14:07
Just a question, are you instantiating regex repeatedly during the search, or once before the search begins?

**Comment by myearwood1** [comment] 2024-04-05 19:04
By the way, when the regex starts with "\" it gets disabled in the search: drop-down of previous searches and cannot be re-selected.

**Comment by Jimrnelson** [comment] 2024-04-05 19:47
You mean begins with a backslash?  "\\" ?

**Comment by Jimrnelson** [comment] 2024-04-05 19:59
> Can you provide any idea of the size of the folder being searched? Total number of files (including sub-folders) maybe, or bytes? How about the number of files in the biggest sub-folder?

**Comment by Jimrnelson** [comment] 2024-04-05 23:49
> Just a question, are you instantiating regex repeatedly during the search, or once before the search begins?

Mike --

It actually looks like regex is instantiated once per GF session (not for each search and definitely not repeatedly during the search)

BTW, using your regular expression as a text, I found that RegExp took about 9 times as long (102 seconds vs 9) than wild card search.  On your massive code base, that would make a huge difference.

That is, in fact, why GF offers other filters, after the search.

**Comment by Jimrnelson** [comment] 2024-04-05 23:57
> BTW, using your regular expression as a text, I found that RegExp took about 9 times as long (102 seconds vs 9) than wild card search. On your massive code base, that would make a huge difference.

So this keeps me from using regular expressions, but I think that there's room for a filter (yup, another) that could be of benefit for regular expression users.

I suggested (earlier) doing a wild card search for 'REPO*FORM', something which ran fast for me (9 seconds) but obviously returned a lot of extraneous matches (600 total matches).

It seems that having a filter which is a regular expression (instead of just wild card) would combine the two nicely, be very fast, and achieve the results you want.

I hope this makes sense.  

I have not considered implementation details.

**Comment by Jimrnelson** [comment] 2024-04-06 23:15
> By the way, when the regex starts with "" it gets disabled in the search: drop-down of previous searches and cannot be re-selected.

This has been addressed in Version 7.0.23 - 2024-04-06 (#212)

BTW, Mike, it would be handier if you created new issues, even for small things like this, so they don't get lost.

**Comment by myearwood1** [comment] 2024-04-08 15:17
Understood and thanks for the change.

**Comment by myearwood1** [comment] 2024-04-08 22:04
Can a GoFish user do a search including OR? repo*form ' OR repo*form "?

**Comment by Jimrnelson** [comment] 2024-04-08 22:22
To do that would require regex; there's no way to do that with wild cards (other than to do distinct searches).

**Comment by Jimrnelson** [comment] 2024-04-08 22:22
I'd like to repeat this request of you on the original topic:

Can you provide any idea of the size of the folder being searched? Total number of files (including sub-folders) maybe, or bytes? How about the number of files in the biggest sub-folder?

**Comment by myearwood1** [comment] 2024-04-08 23:40
I don't see the value in answering the question. The number of reports is 2415. 3044 scx files. 1200 prg files. The regex - and as far as I can tell - much of GoFish is spinning its wheels. 

Where this code does a filetostr on the .prg text, it would save time to pass m.lcCode by reference like so This.SearchInCode(@m.lcCode

```
		If !Empty(This.oSearchOptions.cSearchExpression)
			Try
					lcCode     = Filetostr(m.tcFile) && File could be in use by some other app and can't be read in
					llReadFile = .T.
				Catch
					This.SetSearchError('Could not open file [' + m.tcFile + '] for reading.')
					llReadFile = .F.
			Endtry
			If !m.llReadFile
				Select (m.lnSelect)
				Return 0
			Endif

			llHasMethods = Inlist(Upper(m.loFileResultObject.MatchType) + ' ', 'PRG ', 'MPR ', 'H ')
			lnMatchCount = This.SearchInCode(m.lcCode, m.loFileResultObject, m.llHasMethods)

```
Likewise in SearchInCode when it passes tcCode to This.oRegExForSearchInCode.Execute

**Comment by Jimrnelson** [comment] 2024-04-08 23:58
> I don't see the value in answering the question.

Since I can't duplicate the environment where this is happening, I am trying to get some idea of the magnitude of your search scope.

There are at least two different things explaining what is going on for you here:

1. The number of files being searched is so large that this might be entirely an ADIR failure. From your earlier posts, it seems like ADir get dramatically slower as the number of files grows (much worse than linear).  Thus the question about the number of files.  
And, actually, I was interested in the total number of files, not by type, just all the files, including those that would be skipped (bak, etc,) since they would be include in the ADIR result.
2. Regex 

My testing with Regex vs wild card searches is that it takes about 9 times as long.

Can you do a plain REPORT FORM search on the same folder?  I want to know how long that takes, it will eliminate the RegEx contribution.

There are two things I am hoping to add eventually as enhancements, once I know enough about what's going on:

1. DIRX
2. Optimizing RegEx so that it's time is more in sync with wild card search AND extending it so it also can search entire statements and not just single statements.

**Comment by myearwood1** [comment] 2024-04-09 15:35
Thanks for your perspective. I can help I have approximately 20000 files. 
DirX built a cursor of the entire app folder, recursively, in 0.426 seconds. That includes doing a replace command and building an index.
https://github.com/ChristianEhlscheid/vfp2c32

**Comment by myearwood1** [comment] 2024-04-09 21:46
I see in GoFish the user can select types of files. If I build the following command in DirX, based on their choices:
dirx("c_temp","forms\*.scx;reports\*.frx;progs\*.prg;libs\*.vcx;menus\*.mnx")
I get a cursor of 6485 records before I can blink. You could also have it scan the entire directory tree recursively for a specific file type and process them.

**Comment by Jimrnelson** [comment] 2024-04-10 21:24
@myearwood1 

I've been having some problems understanding why the search on your massive folder took so long without completing.

In today's update to GF (7.0.24) I have added a little something that might help me a little.  After you run a search, there's a label at the upper right of the form indicating the number of matches and elapsed time.  What I have added is that if you click on that label you get some more detailed information.

So, I am asking that you run three tests (Plain / Wild Card / RegEx) in your massive folder, each time with a search expression that will find no results.  After each text, click on that label (it brings up a messagebox) and then paste that image into a return message.  

I am hoping this will help reveal where the issue is.

Also, please don't press any keys during those searches.  I know Esc is supposed to interrupt, but I'd rather not have that as part of the mix.

**Comment by myearwood1** [comment] 2024-04-12 14:58
I appreciate the addition of the number of files being searched. Don't make the mistake of thinking the creation of the files to be processed is the problem. The issue is using all kinds of high level loops to scan through whatever thing holds the file list, with multiple calls to methods of objects. The GF Janitor fails when adir() produces too large an array.

Plain search for "this will not match. this will not match"
![image](https://github.com/VFPX/GoFish/assets/5750619/5386db52-05c0-4663-991f-068ff3987d40)

Wild card search for "this will not match. this will not match"
![image](https://github.com/VFPX/GoFish/assets/5750619/f89b57c5-85bc-419a-a0f9-9458e0866403)

Here's the first two. I will get the regex later.

**Comment by myearwood1** [comment] 2024-04-12 16:54
By the way, just to demonstrate the problem of too much high level code and not thinking outside the box... the following code scans the same 19,000+ files (to extract just the text versions), converts the files to code via filetostr and searches for "%REPO% FORM" and does it in 5.2 seconds, not 34 seconds.

`clear all

a=seconds()

*get the files

IF DirX('c_TheFiles','VFPPATH\*.*','',.T.) > 0

	*Which TEXT / PRG files contain "REPORT FORM"?

	SELECT 0

	select filename,fname,fileext,filename as FileContent ;
	from c_TheFiles ;
	where ;
		fname not in ('MYSEARCH','FOXUSER') ;
		AND FILEEXT IN ('PRG','VCA','SCA','FRA','LBA') ;
	INTO CURSOR c_JustThese nofilter
	
	use dbf("c_JustThese") again shared in 0 alias c_justtext

	select c_justtext
	replace all filecontent with filetostr(filename)
	
	select * ;
		from c_justtext ;
		where ;
		FileContent like "%REPO% FORM" ;
		into cursor ;
		c_Results nofilter
	
endif

use in (select("c_thefiles"))

?seconds()-m.a
`
I wish I could figure out how to get the filetostr to happen in the query, and then extract the code from the vcx/scx/frx/lbx

**Comment by Jimrnelson** [comment] 2024-04-12 18:44
@myearwood1 

Mike -- 

I am well aware of this suggested approach which you have also described in another issue (#142).  That issue remains open as I have yet to delve into it.

There are a couple things with this that would have to be worked out:

- This issue assumes that there are text files ("A" files) to simplify searching binaries.  GF cannot assume that such text files exist, that they are "A" files and not "2" files, nor that they are current.
- If this were modified to reference the binary files directly, it would have to handle the issue of the file being already open (which would create "access denied" errors.)

This solution is indeed very fast if all that is desired is the list of files with a match.  However, GF goes way beyond that to extract where the matches occur in each file.  I have to assume that there is significant processing time involved in that.  Thus, I think that the timing comparison is weak.

Before I get to this particular issue in any more detail, I will be looking into some significant improvements to RegEx searching.

**Comment by myearwood1** [comment] 2024-04-12 22:18
I agree with you. I would have to expand that example to equal you, but I did tell GoFish to search the same file types I did.

**Comment by Jimrnelson** [comment] 2024-04-12 22:28
Yes, that will take some work to make it provide all the features GF provides.

For now, I am letting it lay fallow until most of the other issues are addressed.

**Comment by Jimrnelson** [comment] 2024-04-18 14:27
@myearwood1 

Mike, can you check to see if this is still an issue?  I am hoping that the recent RegEx change would have fixed it.

That is, really hoping, as I have no other guesses.

**Comment by myearwood1** [comment] 2024-04-18 14:52
Yes it is resolved. My point was there are ways to get things to go really fast, despite so many naysayers. You sir have my thanks for working through this with me.

**Closed** 2024-04-18 15:19 UTC
